
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update  
  datasource:
    url: jdbc:postgresql://localhost:5432/quiz
    username: postgres
    password: 12345
    driverClassName: org.postgresql.Driver
  sql:
   init:
    platform: postgres
  application:
    name: QUESTION-SERVICE

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
            
